---
permalink: deploy/ha-three-node-deployment.html 
sidebar: sidebar 
keywords:  
summary: HA는 소규모, 중간 규모 또는 대규모 구성으로 구성할 수 있습니다. 
---
= HA 구성을 배포합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
소규모, 중간 규모 또는 대규모 구성으로 HA 3개 노드를 구성할 수 있습니다. HA 구축에서는 Trident를 사용하여 서비스 데이터를 저장합니다.

* 소형 HA 3개 노드는 8개의 CPU와 노드당 16GB RAM을 포함합니다.
* 중간 규모 HA 3개 노드에 CPU 12개와 노드당 24GB RAM이 포함됩니다.
* 대규모 HA 3개 노드에 16개의 CPU와 노드당 32GB RAM이 포함됩니다.


* 시작하기 전에 *

이 작업은 소규모, 중간 규모 또는 높은 구성으로 HA 3개 노드를 설치하는 방법에 대한 지침을 제공합니다.


NOTE: 콘텐츠 라이브러리를 생성하는 것은 HA 3노드 구성을 구축하기 위한 필수 단계입니다. link:../deploy/download-ontap-tools.html["콘텐츠 라이브러리를 만듭니다"]절차는 섹션을 참조하십시오. 자세한 내용은 https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html["콘텐츠 라이브러리 만들기 및 사용"] 블로그 를 참조하십시오.

OVA를 콘텐츠 라이브러리로 가져왔는지 확인합니다. 콘텐츠 라이브러리의 이름과 OVA 항목에 지정한 라이브러리 항목 이름을 간편하게 보관합니다.


NOTE: 구축을 진행하기 전에 ONTAP 도구를 설치하는 동안 인벤토리에 있는 클러스터의 DRS(Distributed Resource Scheduler)를 '보존적'으로 설정합니다. 이렇게 하면 설치 중에 VM이 마이그레이션되지 않습니다.

* 단계 *

. vSphere 서버에 로그인합니다.
. 생성한 리소스 풀 또는 OVA를 배포할 클러스터 또는 호스트로 이동합니다.
. 필요한 위치를 마우스 오른쪽 버튼으로 클릭하고 * Deploy OVF template... * 를 선택합니다.
+

NOTE: VMware vSphere 가상 머신용 ONTAP 툴을 관리하는 VVOL 데이터 저장소에 배포하지 마십시오.

. URL을 통해 _.ova_ 파일의 OVA 파일을 선택하거나 _.ova_ 파일이 저장된 폴더를 찾은 후 * 다음 * 을 클릭합니다.
. 컨텐츠 라이브러리에서 VMware vSphere용 ONTAP 툴을 배포하려면 다음을 따르십시오.
+
.. 콘텐츠 라이브러리로 이동하여 배포할 라이브러리 항목을 클릭합니다.
.. 이 템플릿의 새 VM * 을 클릭하십시오 * Actions * > *


. 컴퓨터 리소스를 선택하고 * 다음 * 을 클릭합니다.
. 템플릿의 세부 정보를 검토하고 * 다음 * 을 클릭합니다.
. 라이센스 계약을 읽고 동의한 후 * Next * 를 클릭합니다.
. 배포 구성을 선택하고 * 다음 * 을 클릭합니다.
. 구성 및 디스크 파일의 스토리지를 선택하고 * 다음 * 을 클릭합니다.
. 각 소스 네트워크에 대한 대상 네트워크를 선택하고 * 다음 * 을 클릭합니다.
. Customize template * 창에서 필수 필드를 입력하고 * Next * 를 클릭합니다.
+
** SVM 범위를 사용하도록 설정한 경우 관리 IP 주소를 사용하여 SVM 지원을 이미 사용하도록 설정해야 합니다.
** 여기에 제공된 정보는 설치 과정 중에 올바른 패턴에 대해 검증됩니다. 일치하지 않는 경우 웹 콘솔에 오류 메시지가 표시되고 제공된 잘못된 정보를 수정하라는 메시지가 표시됩니다.
** 호스트 이름은 대문자(A-Z), 소문자(a-z), 숫자(0-9) 또는 하이픈(-) 특수 문자로 구성되어야 합니다. 이중 스택을 구성하려면 IPv6 주소에 매핑된 호스트 이름을 지정합니다.


. 완료 준비 * 창에서 세부 정보를 검토하고 * 마침 * 을 선택합니다.
+
구축 작업이 생성되면 vSphere 작업 표시줄에 진행 상황이 표시됩니다.

. 작업 완료 후 VM의 전원을 켭니다.
+
설치가 시작됩니다. VM의 웹 콘솔에서 설치 진행률을 추적할 수 있습니다. 설치 과정에서 노드 구성이 검증됩니다. OVF 양식의 Customize(사용자 지정) 템플릿 아래에 있는 여러 섹션에 제공된 입력의 유효성을 검사합니다. 불일치가 발생할 경우 대화 상자에 시정 조치를 취하라는 메시지가 표시됩니다.

. 대화 상자 프롬프트에서 필요한 사항을 변경합니다. Tab 버튼을 사용하여 패널을 탐색하고 * OK * 를 선택합니다.
+
제공된 값의 유효성을 다시 검사합니다. VMware vSphere용 ONTAP 툴을 사용하면 잘못된 값을 세 번 수정할 수 있습니다. 세 번 시도해도 문제를 해결할 수 없는 경우 제품 설치가 중지되고 새 VM에서 설치를 시도하는 것이 좋습니다.



설치가 완료되면 웹 콘솔에 VMware vSphere용 ONTAP 툴의 상태가 표시됩니다.
