---
permalink: deploy/nonha-deployment.html 
sidebar: sidebar 
keywords:  
summary: 소형 또는 중형 구성으로 HA가 아닌 단일 노드를 구성할 수 있습니다. 
---
= HA가 아닌 단일 노드 구성을 구현합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
HA가 아닌 단일 노드 구성을 소형 또는 중형 구성으로 구축할 수 있습니다.

* HA가 아닌 소형 구성에는 CPU 8개와 16GB RAM이 포함됩니다.
* 중형 비 HA 구성에는 CPU 12개와 24GB RAM이 포함됩니다.


* 시작하기 전에 *

네트워크 경로가 있는지 확인합니다. 스토리지 데이터 네트워크는 VM 관리 네트워크에서 액세스할 수 있어야 합니다. 예를 들어, ONTAP에 로그인한 후 _network route create -vserver <SVM> -destination 0.0.0.0/0 -gateway <gateway_ip>_ 명령을 실행합니다

* 단계 *

. vSphere 서버에 로그인합니다.
. 생성한 리소스 풀 또는 OVA를 배포할 클러스터 또는 호스트로 이동합니다.
. 필요한 위치를 마우스 오른쪽 버튼으로 클릭하고 * Deploy OVF template... * 를 선택합니다.
+

NOTE: VMware vSphere 가상 머신용 ONTAP 툴을 관리하는 VVOL 데이터 저장소에 배포하지 마십시오.

. URL을 통해 _.ova_ 파일의 OVA 파일을 선택하거나 _.ova_ 파일이 저장된 폴더를 찾은 후 * 다음 * 을 클릭합니다.
. 컴퓨터 리소스를 선택하고 * 다음 * 을 클릭합니다.
. 템플릿의 세부 정보를 검토하고 * 다음 * 을 클릭합니다.
. 사용권 계약을 읽고 동의합니다.
. 배포 구성을 선택하고 * 다음 * 을 클릭합니다.
+
고급 구축 옵션에서는 Trident를 ONTAP를 위한 동적 스토리지 프로비저닝으로 사용하여 볼륨을 생성하고 쉬운 구축에서는 로컬 스토리지를 사용하여 볼륨을 생성합니다.

. 구성 및 디스크 파일의 스토리지를 선택하고 * 다음 * 을 클릭합니다.
. 각 소스 네트워크에 대한 대상 네트워크를 선택하고 * 다음 * 을 클릭합니다.
. Customize template * 에 필요한 세부 정보를 입력하고 * Next * 를 클릭합니다
+
** SVM 범위를 사용하도록 설정한 경우 관리 IP 주소를 사용하여 SVM 지원을 이미 사용하도록 설정해야 합니다.
** 여기에 제공된 정보는 설치 과정 중에 올바른 패턴에 대해 검증됩니다. 일치하지 않는 경우 웹 콘솔에 오류 메시지가 표시되고 제공된 잘못된 정보를 수정하라는 메시지가 표시됩니다.
** 호스트 이름은 대문자(A-Z), 소문자(a-z), 숫자(0-9) 또는 하이픈(-) 특수 문자로 구성되어야 합니다. 이중 스택을 구성하려면 IPv6 주소에 매핑된 호스트 이름을 지정합니다.


. 완료 준비 * 창에서 세부 정보를 검토하고 * 마침 * 을 선택합니다.
+
구축 작업이 생성되면 vSphere 작업 표시줄에 진행 상황이 표시됩니다.

. 작업 완료 후 VM의 전원을 켭니다.
+
설치가 시작됩니다. VM의 웹 콘솔에서 설치 진행률을 추적할 수 있습니다. 설치 과정에서 노드 구성이 검증됩니다. OVF 양식의 Customize(사용자 지정) 템플릿 아래에 있는 여러 섹션에 제공된 입력의 유효성을 검사합니다. 일치하지 않는 경우 대화 상자에 시정 조치를 취하라는 메시지가 표시됩니다.

. 대화 상자 프롬프트에서 필요한 사항을 변경합니다. Tab 버튼을 사용하여 패널을 탐색하고 * OK * 를 선택합니다.
+
제공된 값의 유효성을 다시 검사합니다. VMware vSphere용 ONTAP 툴을 사용하면 잘못된 값을 세 번 수정할 수 있습니다. 세 번 시도해도 문제를 해결할 수 없는 경우 제품 설치가 중지되고 새 VM에서 설치를 시도하는 것이 좋습니다.



설치가 완료되면 웹 콘솔에 VMware vSphere용 ONTAP 툴의 상태가 표시됩니다.
