---
permalink: deploy/ontap-tools-deployment.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere 어플라이언스용 ONTAP 툴은 항상 NFS/VMFS 데이터 저장소를 지원하는 핵심 서비스를 갖춘 소규모 단일 노드로 구축됩니다. 
---
= VMware vSphere용 ONTAP 툴을 구축합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere 어플라이언스용 ONTAP 툴은 항상 NFS/VMFS 데이터 저장소를 지원하는 핵심 서비스를 갖춘 소규모 단일 노드로 구축됩니다.

* 시작하기 전에 *

VMware의 컨텐츠 라이브러리는 VM 템플릿, vApp 템플릿 및 기타 유형의 파일을 저장하는 컨테이너 객체입니다. 콘텐츠 라이브러리를 사용한 배포는 네트워크 연결에 의존하지 않으므로 원활한 환경을 제공합니다.


NOTE: 클러스터의 모든 호스트가 액세스할 수 있도록 컨텐츠 라이브러리를 공유 데이터 저장소에 저장해야 합니다. 어플라이언스 설정을 HA 구성으로 변경하기 전에 OVA를 저장할 콘텐츠 라이브러리를 만들어야 합니다. 업로드한 콘텐츠 라이브러리 서식 파일은 배포 후 삭제해서는 안 됩니다.


NOTE: 나중에 HA 배포를 활성화하려면 ONTAP 툴을 호스팅하는 가상 시스템을 ESXi 호스트에 직접 배포해서는 안 됩니다. 대신 클러스터 또는 리소스 풀에 구축되어야 합니다.

적합한 콘텐츠 라이브러리가 아직 없는 경우 다음 단계에 따라 콘텐츠 라이브러리를 만드십시오.


NOTE: 소규모 단일 노드 배포만 사용하려는 경우에는 콘텐츠 라이브러리를 만들 필요가 없습니다.

.  `.zip`에서 VMware vSphere용 ONTAP 툴에 대한 바이너리(_.ova_)와 서명된 인증서가 포함된 파일을 https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp Support 사이트"^] 다운로드합니다.
. 을 사용하여 vSphere Client에 로그인합니다 `\https://<vcenterip>/<ui>`
. vSphere Client 옆에 있는 가로 줄임표를 선택하고 * Content library * 를 선택합니다.
. 페이지 오른쪽에서 * 만들기 * 를 선택합니다.
. 라이브러리 이름을 지정하고 콘텐츠 라이브러리를 만듭니다.
. 만든 콘텐츠 라이브러리로 이동합니다.
. 페이지 오른쪽의 * Actions * 를 선택하고 * Import item * 을 선택한 후 OVA 파일을 가져옵니다.



NOTE: 자세한 내용은 https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html["콘텐츠 라이브러리 만들기 및 사용"] 블로그 를 참조하십시오.

OVA를 콘텐츠 라이브러리로 가져왔는지 확인합니다.


NOTE: 구축을 진행하기 전에 ONTAP 도구를 설치하는 동안 인벤토리에 있는 클러스터의 DRS(Distributed Resource Scheduler)를 '보존적'으로 설정합니다. 이렇게 하면 설치 중에 VM이 마이그레이션되지 않습니다.

.단계
.  `.zip`에서 VMware vSphere용 ONTAP 툴에 대한 바이너리(_.ova_)와 서명된 인증서가 포함된 파일을 https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp Support 사이트"^] 다운로드합니다. 콘텐츠 라이브러리로 OVA를 가져온 경우 이 단계를 건너뛰고 콘텐츠 라이브러리에서 직접 배포할 수 있으므로 다음 단계를 진행할 수 있습니다.
. vSphere 서버에 로그인합니다.
. 생성한 리소스 풀 또는 OVA를 배포할 클러스터 또는 호스트로 이동합니다.
. 필요한 위치를 마우스 오른쪽 버튼으로 클릭하고 * Deploy OVF template... * 를 선택합니다.
+

NOTE: VMware vSphere 가상 머신용 ONTAP 툴을 관리하는 VVOL 데이터 저장소에 저장하지 마십시오.

. OVA 파일을 _.ova_ 파일의 URL을 통해 선택하거나 _.ova_ 파일이 저장된 폴더를 찾은 후 * 다음 * 을 선택합니다.
. 컨텐츠 라이브러리에서 VMware vSphere용 ONTAP 툴을 배포하려면 다음을 따르십시오.
+
.. 콘텐츠 라이브러리로 이동하여 배포할 라이브러리 항목을 선택합니다.
.. 이 템플릿에서 * Actions * > * New VM * 을 선택합니다


. Select a name and folder * for the virtual machine 창에서 가상 머신 이름을 입력하고 가상 머신의 위치를 선택합니다. * 이 가상 시스템의 하드웨어 사용자 정의 * 확인란을 선택하면 * 완료 준비 * 창에 도달하기 전에 * 하드웨어 사용자 정의 * 라는 단계가 활성화됩니다.
. 컴퓨터 리소스를 선택하고 * 다음 * 을 선택합니다. 배포된 VM의 전원을 자동으로 켜기 * 확인란을 선택할 수 있습니다.
. 템플릿의 세부 정보를 검토하고 * 다음 * 을 선택합니다.
. 사용권 계약을 읽고 동의한 후 * Next * 를 선택합니다.
. 구성 및 디스크 파일의 스토리지를 선택하고 * Next * 를 선택합니다.
. 각 소스 네트워크에 대한 대상 네트워크를 선택하고 * 다음 * 을 선택합니다.
. Customize template * 창에서 필수 필드를 입력하고 * Next * 를 선택합니다.
+
** 여기에 제공된 정보는 설치 과정 중에 올바른 패턴에 대해 검증됩니다. 일치하지 않는 경우 웹 콘솔에 오류 메시지가 표시되고 제공된 잘못된 정보를 수정하라는 메시지가 표시됩니다.
** 호스트 이름은 대문자(A-Z), 소문자(a-z), 숫자(0-9) 또는 하이픈(-) 특수 문자로 구성되어야 합니다. 이중 스택을 구성하려면 IPv6 주소에 매핑된 호스트 이름을 지정합니다.
+

NOTE: Pure IPv6는 지원되지 않습니다. 혼합 모드는 IPv6 주소와 IPv4 주소가 모두 있는 VLAN에서 지원됩니다.



. 하드웨어 사용자 정의* 창에서 CPU 핫 추가 및 메모리 핫 플러그를 활성화해야 합니다.
. 완료 준비 * 창에서 세부 정보를 검토하고 * 마침 * 을 선택합니다.
+
구축 작업이 생성되면 vSphere 작업 표시줄에 진행 상황이 표시됩니다.

. 작업 완료 후 VM의 전원을 켭니다.
+

NOTE: 전원을 켜기 전에 VM에 CPU 및 메모리 모두에 대해 핫 플러그인이 활성화되어 있는지 확인합니다.



VM의 웹 콘솔에서 설치 진행률을 추적할 수 있습니다.

OVF 양식에 입력한 값이 일치하지 않는 경우 수정 조치를 취하라는 대화 상자가 나타납니다. 탭 버튼을 사용하여 대화 상자에서 필요한 사항을 변경하고 "확인"을 선택합니다. 문제를 해결하기 위해 세 번 시도할 수 있습니다. 세 번 시도해도 문제가 계속되면 설치 프로세스가 중단되며 새 VM에서 설치를 다시 시도하는 것이 좋습니다.
