---
permalink: protect/configure-storage-replication-adapter-for-san-environment.html 
sidebar: sidebar 
keywords:  
summary: 'VMware Live Site Recovery용 스토리지 복제 어댑터\(SRA\)를 실행하기 전에 스토리지 시스템을 설정해야 합니다.' 
---
= SAN 및 NAS 환경용 ONTAP tools에서 SRA 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware Live Site Recovery용 SRA(Storage Replication Adapter)를 실행하기 전에 스토리지 시스템을 설정해야 합니다.



== SAN 환경에 맞게 SRA 구성


NOTE: SRA 워크플로의 일관성 그룹은 Unified 및 ASA r2 스토리지 시스템 모두에서 SAN 프로토콜(iSCSI 및 Fibre Channel)을 통해서만 지원됩니다.

.시작하기 전에
보호된 사이트와 복구 사이트에 다음 프로그램이 설치되어 있어야 합니다.

* VMware Live Site Recovery: VMware 사이트는 VMware Live Site Recovery에 대한 설치 설명서를 제공합니다.
+
https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/about-vmware-live-site-recovery-installation-and-configuration.html["VMware Live Site Recovery에 대해 알아보십시오"]

* SRA: VMware Live Site Recovery에 어댑터를 설치합니다.


iSCSI 프로토콜 구성의 경우 SRA 워크플로우를 실행하기 전에 다음 사항에 유의하십시오.

* *보호된 사이트*: iSCSI 스토리지 어댑터 및 데이터 LIF 세부 정보는 데이터 저장소를 프로비저닝할 때 자동으로 구성됩니다. 수동 구성은 필요하지 않습니다.
* *복구 사이트*: 재해 복구를 위한 리소스 매핑에 포함된 각 ESXi 호스트에서 iSCSI 스토리지 어댑터를 수동으로 구성해야 합니다. 각 호스트에서 어댑터를 개별적으로 구성하는 번거로움을 피하려면 SRA 워크플로가 구성된 SVM을 사용하여 복구 사이트에 iSCSI 유형의 자리 표시자 데이터 저장소를 생성하십시오. 이렇게 하면 iSCSI 어댑터와 필요한 데이터 LIF IP 주소가 매핑된 모든 ESXi 호스트에 자동으로 추가됩니다. 자세한 내용은 link:../protect/configure-placeholder-datastores.html["ONTAP tools에서 플레이스홀더 데이터 저장소를 구성합니다"]을 참조하십시오.


.단계
. 운영 ESXi 호스트가 보호 사이트의 운영 스토리지 시스템에 있는 LUN에 연결되어 있는지 확인합니다.
. 운영 스토리지 시스템에서 LUN이 `ostype` 옵션이 _VMware_로 설정된 igroup에 있는지 확인합니다.
. 복구 사이트의 ESXi 호스트에 스토리지 가상 머신(SVM)에 대한 적절한 iSCSI 및 파이버 채널 연결이 있는지 확인합니다.  보조 사이트 ESXi 호스트는 보조 사이트 스토리지에 액세스할 수 있어야 하고, 기본 사이트 ESXi 호스트는 기본 사이트 스토리지에 액세스할 수 있어야 합니다.
+
이 작업은 ESXi 호스트에 SVM 또는 에 로컬 LUN이 연결되어 있는지 확인하여 수행할 수 있습니다 `iscsi show initiators` SVM에서 명령을 실행합니다.
ESXi 호스트에서 매핑된 LUN에 대한 LUN 액세스를 확인하여 iSCSI 접속을 확인합니다.





== NAS 환경에 대한 SRA 구성


NOTE: SRA 워크플로에서 NFS에 대한 일관성 그룹은 지원되지 않습니다. NFS 데이터 저장소 볼륨이 일관성 그룹에 배치되고 보호되는 경우 장치 검색 작업이 실패합니다. SRA를 사용하여 NFS 데이터 저장소를 보호할 때는 일관성 그룹을 사용하지 마십시오.

.시작하기 전에
보호된 사이트와 복구 사이트에 다음 프로그램이 설치되어 있어야 합니다.

* VMware Live Site Recovery: VMware 사이트에서 VMware Live Site Recovery에 대한 설치 설명서를 찾을 수 있습니다. https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/about-vmware-live-site-recovery-installation-and-configuration.html["VMware Live Site Recovery에 대해 알아보십시오"]
* SRA: VMware Live Site Recovery와 SRA 서버에 어댑터를 설치합니다.


.단계
. 보호 사이트의 데이터 저장소에 vCenter Server에 등록된 가상 머신이 포함되어 있는지 확인합니다.
. 보호 대상 사이트의 ESXi 호스트가 스토리지 가상 머신(SVM)에서 NFS 엑스포트 볼륨을 마운트했는지 확인하십시오.
. Array Manager 마법사를 사용하여 VMware Live Site Recovery에 어레이를 추가할 때 *NFS Addresses* 필드에 NFS 엑스포트가 있는 유효한 IP 주소가 지정되어 있는지 확인하십시오. *NFS Addresses* 필드에 NFS 호스트 이름 또는 FQDN을 사용하지 마십시오.
. 를 사용합니다 `ping` 복구 사이트의 각 ESXi 호스트에서 명령을 실행하여 호스트에 SVM에서 NFS 엑스포트를 지원하는 데 사용되는 IP 주소를 액세스할 수 있는 VMkernel 포트가 있는지 확인합니다.

