---
permalink: protect/enable-storage-replication-adapter.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere용 ONTAP 툴은 SRA 기능을 사용하여 재해 복구를 구성할 수 있는 옵션을 제공합니다. 
---
= 데이터 저장소를 보호하려면 ONTAP tools에서 SRA를 구성하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere용 ONTAP 툴은 SRA 기능을 사용하여 재해 복구를 구성할 수 있는 옵션을 제공합니다.

.시작하기 전에
* vCenter Server 인스턴스를 설정하고 ESXi 호스트를 구성해야 합니다.
* VMware vSphere용 ONTAP 툴을 배포해야 합니다.
*  `.tar.gz`에서 SRA Adapter 파일을 다운로드해야 https://mysupport.netapp.com/site/products/all/details/otv10/downloads-tab["NetApp Support 사이트"^] 합니다.
* SRA 워크플로를 실행하기 전에 소스 및 대상 ONTAP 클러스터 모두에 동일한 사용자 지정 SnapMirror 일정이 있어야 합니다.
* link:../manage/enable-services.html["VMware vSphere 서비스에 대해 ONTAP 툴을 사용하도록 설정합니다"] SRA 기능을 활성화합니다.


.단계
. URL:을 사용하여 VMware Live Site Recovery 어플라이언스 관리 인터페이스에 로그인한 `\https://:<srm_ip>:5480` 다음 VMware VMware Live Site Recovery 어플라이언스 관리 인터페이스의 스토리지 복제 어댑터로 이동합니다.
. 새 어댑터 * 를 선택합니다.
. SRA 플러그인용 _.tar.gz_installer를 VMware Live Site Recovery에 업로드합니다.
. 어댑터를 다시 검색하여 VMware Live Site Recovery Storage Replication Adapters 페이지에서 세부 정보가 업데이트되었는지 확인합니다.



NOTE: 장애 조치 후에는 확장, 마운트, 삭제와 같은 작업을 데이터 저장소에서 수행할 수 없습니다.  데이터 저장소 검색을 수행하여 적절한 상황에 맞는 메뉴 작업을 새로 고치고 표시합니다.


NOTE: 각 재보호 작업 후에는 두 사이트 모두에서 저장소 검색을 수행해야 합니다.

SRA 보호 기능이 있는 새로운 설정에서는 항상 테스트 장애 조치를 실행하세요.  테스트 장애 조치를 건너뛰면 재보호 작업이 실패할 수 있습니다.

팬아웃 구성에서 SnapMirror Active Sync 장애 조치가 발생하여 SnapMirror 소스가 자동 장애 조치 이중화 및 비동기 SnapMirror 위해 사이트 B로 변경된 후 사이트 B와 C 간에 테스트 장애 조치를 실행합니다. 이 단계를 건너뛰면 재보호 작업이 실패할 수 있습니다.

.관련 정보
https://docs.netapp.com/us-en/netapp-solutions-virtualization/vmware/vmw-nfs-vlsr.html#scenario-overview["VMware Site Recovery Manager를 사용하여 NFS 데이터 저장소에 대한 재해 복구 구성"]
