---
permalink: protect/update-credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: VMware Live Site Recovery가 SRA와 통신하려면 자격 증명을 수정한 경우 VMware Live Site Recovery 서버에서 SRA 자격 증명을 업데이트해야 합니다. 
---
= ONTAP tools에서 SRA 자격 증명 업데이트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware Live Site Recovery가 SRA와 통신하려면 자격 증명을 수정한 경우 VMware Live Site Recovery 서버에서 SRA 자격 증명을 업데이트해야 합니다.

.시작하기 전에
항목에서 언급한 단계를 실행했어야 link:../protect/configure-on-srm-appliance.html["VMware Live Site Recovery 어플라이언스에서 SRA 구성"]합니다.

.단계
. VMware Live Site Recovery 시스템에서 캐시된 ONTAP tools 자격 증명을 삭제하려면 다음 명령을 실행하십시오.
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd conf/`
.. `rm -rf *`


. Perl 명령을 실행하여 새 자격 증명으로 SRA를 구성합니다.
+
.. `cd ..`
.. `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <OTV_ADMIN_USERNAME> --otv-password <OTV_ADMIN_PASSWORD> --vcenter-guid <VCENTER_GUID>` 암호 값을 따옴표로 묶어야 합니다.
+
스토리지 자격 증명이 저장되었음을 확인하는 성공 메시지가 표시됩니다. SRA는 제공된 IP 주소, 포트 및 자격 증명을 사용하여 SRA 서버와 통신할 수 있습니다.







== 인증서 변경 후 VMware Live Site Recovery 어플라이언스에서 vCenter 재구성

vCenter 인증서가 변경되는 경우(예: vCenter 업그레이드 후) Site Recovery 확장 프로그램에서 지문 불일치 오류가 발생할 수 있습니다. 다음 단계를 수행하여 이 문제를 해결하십시오.

.단계
. VMware Live Site Recovery 어플라이언스에서 vCenter 재구성
+
.. 브라우저에서 VMware Live Site Recovery 어플라이언스 관리 인터페이스를 엽니다. `\https://<SRM_IP>:5480`
.. * 요약 * 탭을 선택합니다.
.. vCenter Server 연결에 대해 *재구성*을 선택하십시오.
+
이 작업은 vCenter에서 최신 인증서 지문을 가져와 수락합니다.



. 사이트 페어링 재연결(오류가 지속되는 경우)
+
재구성 후에도 지문 불일치 오류가 계속 발생하는 경우:

+
.. vCenter 사용자 인터페이스에 로그인합니다.
.. *Site Recovery* 확장 프로그램으로 이동합니다.
.. *Site Pairing* 섹션을 찾으십시오.
.. 업데이트된 인증서를 사용하여 사이트 페어링을 다시 설정하려면 *다시 연결*을 선택하십시오.



