---
permalink: protect/verify-the-replicated-storage-environment.html 
sidebar: sidebar 
keywords: SRA, storage replication adapter, storage discovery, SnapMirror, custom policy, array pairing, VMware Live Site Recovery 
summary: 'SRA(Storage Replication Adapter\)를 구성한 후 보호 사이트와 복구 사이트가 성공적으로 페어링되었는지 확인해야 합니다. 복제된 스토리지 시스템은 보호 사이트와 복구 사이트 모두에서 검색할 수 있어야 합니다.' 
---
= ONTAP tools에서 복제된 스토리지 시스템을 검증합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SRA(Storage Replication Adapter)를 구성한 후 보호 사이트와 복구 사이트가 성공적으로 페어링되었는지 확인해야 합니다. 복제된 스토리지 시스템은 보호 사이트와 복구 사이트 모두에서 검색할 수 있어야 합니다.

.시작하기 전에
* 스토리지 시스템을 구성해야 합니다.
* VMware Live Site Recovery 어레이 관리자를 사용하여 보호 사이트와 복구 사이트를 페어링해야 합니다.
* SRA에 대한 테스트 페일오버 작업 및 페일오버 작업을 수행하기 전에 FlexClone 라이센스 및 SnapMirror 라이센스를 활성화해야 합니다.
* 소스 사이트와 대상 사이트에 동일한 SnapMirror 정책 및 일정이 있어야 합니다.
* 사용자 지정 일정을 사용하는 사용자 지정 SnapMirror 정책을 사용하는 경우 보호 사이트와 복구 사이트 모두에 동일한 일정과 정책을 구성해야 합니다.
* 사용자 지정 SnapMirror 정책(기본 일정 또는 사용자 지정 일정)을 사용하는 경우 새 정책이 인식되도록 ONTAP tools에서 스토리지 검색을 수행해야 합니다. 그렇지 않으면 테스트 페일오버 및 페일오버를 포함한 SRA 워크플로가 실패합니다. 다음 시점에서 스토리지 검색을 수행하십시오.
+
** 복구 사이트에서 사용자 지정 정책을 생성한 후
** 재보호 작업 후에는 보호 대상 사이트에 정책이 다시 생성됩니다.




.단계
. vCenter Server에 로그인합니다.
. *사이트 복구* > *어레이 기반 복제*로 이동합니다.
. 필요한 스토리지 쌍을 선택하고 해당 세부 정보를 확인합니다.
+
보호 사이트 및 복구 사이트에서 상태가 ""Enabled""로 설정된 스토리지 시스템을 검색해야 합니다.


