---
permalink: configure/add-vcenter.html 
sidebar: sidebar 
keywords:  
summary: vCenter Server 인스턴스를 VMware vSphere용 ONTAP 툴에 추가하여 vCenter Server 환경에서 가상 데이터 저장소를 구성, 관리 및 보호할 수 있습니다. 
---
= ONTAP 도구에 vCenter Server 인스턴스 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
vCenter Server 인스턴스를 VMware vSphere용 ONTAP 툴에 추가하여 vCenter Server 환경에서 가상 데이터 저장소를 구성, 관리 및 보호할 수 있습니다. 여러 vCenter Server 인스턴스를 추가하는 경우 ONTAP 도구와 각 vCenter Server 간의 보안 통신을 위해 사용자 지정 CA 인증서가 필요합니다.

.이 작업에 대해
ONTAP 도구는 vCenter Server와 통합되어 vSphere 클라이언트에서 직접 프로비저닝, 스냅샷, 데이터 보호와 같은 스토리지 작업을 수행합니다.

.시작하기 전에
* vCenter Server 인증서에 DNS 및 IP 주소 항목이 모두 포함된 유효한 SAN(Subject Alternative Name) 확장이 있는지 확인하십시오. 예를 들면 다음과 같습니다.
+
[listing]
----
X509v3 extensions:
    X509v3 Subject Alternative Name:
        DNS: vcenter.example.com, DNS: vcenter, IP Address: 192.168.0.50
----
+
인증서에 SAN 확장이 포함되어 있지 않거나 SAN 확장에 올바른 DNS 또는 IP 주소 값이 포함되어 있지 않은 경우 인증서 유효성 검사 오류로 인해 ONTAP tools 작업이 실패할 수 있습니다.

* vCenter Server의 Primary Network Identifier(PNID)는 SAN 세부 정보에 포함되어야 합니다. PNID와 DNS 이름은 동일해야 하며 DNS에서 확인 가능해야 합니다.
* vCenter Server를 배포할 때는 정규화된 도메인 이름(FQDN)을 사용하는 것이 좋으며, 최적의 호환성과 지원을 위해 인증서의 SAN에 DNS Name=machine_FQDN이 포함되도록 해야 합니다.
* 자세한 내용은 VMware 설명서를 참조하십시오.
+
** https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-authentication/vsphere-security-certificates-authentication/certificate-requirements-for-different-solution-paths-authentication.html["vSphere 다양한 솔루션 경로에 대한 인증서 요구 사항"]
** https://knowledge.broadcom.com/external/article/316601/replace-vcenter-machine-ssl-certificate.html["vCenter 머신 SSL 인증서 교체 사용자 지정 인증 기관 서명 인증서"]
** https://knowledge.broadcom.com/external/article/406282/error-subject-alternate-name-san-field-d.html["오류: Subject Alternate Name(SAN) 필드에 PNID가 없습니다. 유효한 인증서를 제공하십시오"]




[NOTE]
====
FQDN을 사용할 수 없는 경우 PNID를 IP 주소로 설정하고 해당 IP 주소를 SAN에 포함할 수 있습니다. 하지만 VMware에서는 이 방법을 권장하지 않습니다.

====
.단계
. 웹 브라우저를 열고 다음 URL로 이동하세요. `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 구축 중에 제공한 VMware vSphere 관리자 자격 증명용 ONTAP 툴을 사용하여 로그인합니다.
. vCenter Server 인스턴스를 온보딩하려면 * vCenters * > * Add * 를 선택합니다. vCenter IP 주소 또는 호스트 이름, 사용자 이름, 암호 및 포트 세부 정보를 제공합니다.
. 고급 옵션에서 vCenter Server 인증서를 자동으로 가져오거나(인증) 수동으로 업로드합니다.
+

NOTE: vCenter 인스턴스를 ONTAP 툴에 추가하기 위해 관리자 계정이 필요하지 않습니다. 제한된 권한을 가진 관리자 계정 없이 사용자 지정 역할을 만들 수 있습니다. 자세한 내용은 을 link:../concepts/rbac-vcenter-use.html["VMware vSphere 10용 ONTAP 툴과 함께 vCenter Server RBAC를 사용하십시오"] 참조하십시오.



ONTAP 툴에 vCenter Server 인스턴스를 추가하면 다음 작업이 자동으로 트리거됩니다.

* ONTAP 도구는 vCenter 클라이언트 플러그인을 원격 플러그인으로 등록합니다.
* 플러그인에 대한 사용자 지정 Privileges 및 API는 vCenter Server 인스턴스에 적용됩니다.
* 사용자 지정 역할이 생성되어 사용자를 관리합니다.
* vSphere 사용자 인터페이스에서 플러그인이 바로 가기로 표시됩니다.

