---
permalink: configure/add-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: 스토리지 백엔드는 ESXi 호스트가 데이터 스토리지에 사용하는 시스템입니다. 
---
= ONTAP tools에 스토리지 백엔드 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere 사용하여 ESXi 호스트의 스토리지 백엔드를 추가하고 관리하세요.  클러스터나 SVM을 온보딩하고, MetroCluster 지원을 활성화하고, 안전한 연결을 위해 인증서를 검증할 수 있습니다.  ONTAP 도구 관리자나 vSphere 클라이언트를 사용하여 스토리지 백엔드를 구성하고, 인증서 상태를 모니터링하고, 클러스터 변경 후 리소스를 수동으로 다시 검색할 수 있습니다.

로컬로 스토리지 백엔드를 추가하려면 ONTAP 도구 인터페이스에서 클러스터 또는 SVM 자격 증명을 사용하세요.  로컬 스토리지 백엔드는 선택한 vCenter Server에서만 사용할 수 있습니다. ONTAP 도구는 vVols 또는 VMFS 데이터 저장소 관리를 위해 SVM을 vCenter Server에 매핑합니다.  VMFS 데이터 저장소와 SRA 워크플로의 경우 클러스터를 전역적으로 매핑하지 않고도 SVM 자격 증명을 사용할 수 있습니다.

글로벌 스토리지 백엔드를 추가하려면 ONTAP 도구 관리자에서 ONTAP 클러스터 자격 증명을 사용하세요.  글로벌 스토리지 백엔드를 사용하면 검색 워크플로를 통해 vVol 관리에 필요한 클러스터 리소스를 식별할 수 있습니다.  멀티테넌트 환경에서는 SVM 사용자를 로컬로 추가하여 vVols 데이터 저장소를 관리할 수 있습니다.

ONTAP 에서 MetroCluster 지원이 활성화된 경우 소스 및 대상 클러스터를 모두 로컬 또는 글로벌 스토리지 백엔드로 온보딩합니다.

.시작하기 전에
인증서에 유효한 SAN(주체 대체 이름) 필드가 포함되어 있는지 확인하세요.  ONTAP 시스템은 SAN 필드를 사용하여 클러스터 및 SVM 관리 LIF를 식별합니다.

[role="tabbed-block"]
====
.ONTAP 도구 관리자 사용
--

NOTE: 멀티 테넌트 설정에서 스토리지 백엔드 클러스터를 글로벌 및 SVM을 로컬에서 추가하여 SVM 사용자 자격 증명을 사용할 수 있습니다.

.단계
. 웹 브라우저에서 ONTAP 도구 관리자를 실행합니다. `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 구축 중에 제공한 VMware vSphere 관리자 자격 증명용 ONTAP 툴을 사용하여 로그인합니다.
. 측면 표시줄에서 * Storage Backend * 를 선택합니다.
. 스토리지 백엔드를 추가하고 서버 IP 주소 또는 FQDN, 사용자 이름 및 암호 세부 정보를 제공합니다.
+

NOTE: IPv4 및 IPv6 주소 관리 LIF가 지원됩니다.

. ONTAP 클러스터 인증서를 자동으로 가져와서 인증서를 인증하거나, 해당 위치를 찾아 수동으로 업로드합니다.
+

NOTE: 필요한 경우 유지 관리 콘솔에서 SAN(주체 대체 이름) 유효성 검사를 비활성화할 수 있습니다. 지침은 다음을 참조하세요.link:../manage/change-valid-flag.html["인증서 유효성 검사 플래그 변경"] .

. 추가하는 스토리지 백엔드가 MetroCluster 구성의 일부인 경우 ONTAP 도구 관리자는 피어링된 클러스터를 추가하라는 팝업 메시지를 표시합니다.  *추가*를 선택하고 MetroCluster 피어 스토리지 백엔드에 대한 세부 정보를 제공합니다.
+

NOTE: ONTAP 시스템이 전환 및 스위치백을 수행한 후 ONTAP 도구 검색을 수동으로 실행합니다.



--
.vSphere Client 사용자 인터페이스 사용
--

NOTE: vVols 데이터 저장소는 vSphere 클라이언트 사용자 인터페이스를 통해 SVM 사용자를 직접 추가하는 것을 지원하지 않습니다.

. vSphere Client에 로그인합니다.
. 바로 가기 페이지의 플러그인 섹션에서 * NetApp ONTAP tools * 를 선택합니다.
. 측면 표시줄에서 * Storage Backend * 를 선택합니다.
. 스토리지 백엔드를 추가하고 서버 IP 주소, 사용자 이름, 암호 및 포트 세부 정보를 제공합니다.
+

NOTE: IPv4 또는 IPv6 관리 LIF를 사용하여 클러스터 기반 자격 증명을 사용하여 스토리지 백엔드를 추가할 수 있습니다.  SVM 사용자를 직접 추가하려면 SVM 관리 LIF와 함께 SVM 기반 자격 증명을 제공하세요.  클러스터가 이미 온보딩된 경우 해당 클러스터에서 SVM 사용자를 다시 온보딩할 수 없습니다.

. ONTAP 클러스터 인증서를 자동으로 가져와서 인증서를 인증하거나, 해당 위치를 찾아 수동으로 업로드합니다.
. 추가된 스토리지 백엔드가 MetroCluster 구성의 일부인 경우 ONTAP 도구는 * MetroCluster 피어 추가* 화면을 표시합니다.  피어 스토리지 백엔드를 추가하려면 *피어 추가*를 선택하세요.
+

NOTE: ONTAP 시스템이 전환 및 스위치백을 수행한 후 ONTAP 도구 검색을 수동으로 실행합니다.



.다음 단계
ONTAP 도구는 새로운 스토리지 백엔드를 보여주기 위해 목록을 업데이트합니다.

--
====
ONTAP 도구는 새로 추가된 스토리지 백엔드를 *스토리지 백엔드* 페이지에 나열합니다.  인증서가 30일 이내에 만료되면 ONTAP 도구는 인증서 만료 날짜 열에 경고를 표시합니다.  만료 후 ONTAP 도구는 스토리지 시스템에 연결할 수 없으므로 스토리지 백엔드를 알 수 없음으로 표시합니다.

.관련 정보
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_configure_clusters.html["MetroCluster 구성으로 클러스터 구성"]
