---
permalink: configure/configure-esx-server-multipath-and-timeout-settings.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere용 ONTAP 툴은 NetApp 스토리지 시스템에 가장 적합한 ESXi 호스트 다중 경로 설정과 HBA 시간 초과 설정을 확인하고 설정합니다. 
---
= ESXi 호스트 설정을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ESXi 서버의 다중 경로 및 시간 초과 설정을 구성하면 데이터 가용성과 무결성을 유지하는 데 도움이 됩니다.  기본 경로를 사용할 수 없게 되면 백업 스토리지 경로로 자동 장애 조치가 가능합니다.



== ESXi 서버 다중 경로 및 시간 초과 설정을 구성합니다

VMware vSphere용 ONTAP 툴은 ESXi 호스트 다중 경로 설정과 NetApp 스토리지 시스템에 가장 적합한 HBA 시간 초과 설정을 확인하고 설정합니다.

.이 작업에 대해
이 프로세스는 설정 및 시스템 부하에 따라 시간이 걸릴 수 있습니다.  최근 작업 패널에서 진행 상황을 볼 수 있습니다.

.단계
. VMware vSphere Web Client 홈 페이지에서 * 호스트 및 클러스터 * 를 선택합니다.
. VMware vSphere Web Client의 바로 가기 페이지에서 플러그인 섹션에서 * NetApp ONTAP tools * 를 선택합니다.
. VMware vSphere용 ONTAP 툴의 개요(대시보드)에서 * ESXi 호스트 규정 준수 * 카드로 이동합니다.
. 권장 설정 적용 * 링크를 선택합니다.
. *권장 호스트 설정 적용* 창에서 NetApp 권장 설정을 사용하도록 업데이트할 호스트를 선택하고 *다음*을 선택합니다.
+

NOTE: ESXi 호스트를 확장하여 현재 값을 볼 수 있습니다.

. 설정 페이지에서 필요한 권장 값을 선택합니다.
. 요약 창에서 값을 확인하고 * Finish * 를 선택합니다. 최근 작업 패널에서 진행 상황을 추적할 수 있습니다.




== ESXi 호스트 값을 설정합니다

ONTAP tools for VMware vSphere 사용하여 ESXi 호스트에서 시간 초과 및 기타 값을 설정하여 최적의 성능과 장애 조치를 구현합니다.  이러한 값은 NetApp 테스트를 기반으로 설정됩니다.

ESXi 호스트에서 다음 값을 설정할 수 있습니다.



=== HBA/CNA 어댑터 설정

다음 매개 변수를 기본값으로 설정합니다.

* Disk.QFullSampleSize 를 참조하십시오
* Disk.QFullThreshold를 참조하십시오
* Emulex FC HBA 시간 초과
* QLogic FC HBA 시간 초과




=== MPIO 설정

MPIO 설정은 NetApp 스토리지 시스템에 가장 적합한 경로를 선택합니다.  MPIO 설정은 최적의 경로를 선택하여 사용합니다.

고성능 환경이거나 단일 LUN 데이터 저장소로 테스트하는 경우 라운드 로빈(VMW_PSP_RR) 경로 선택 정책(PSP)의 부하 분산 설정을 조정하여 성능을 개선합니다.  기본 IOPS 값을 1000에서 1로 설정합니다.


NOTE: MPIO 설정은 NVMe, NVMe/FC 및 NVMe/TCP 프로토콜에는 적용되지 않습니다.



=== NFS 설정

|===


| 매개 변수 | 이 값을 다음으로 설정... 


| NET.TcpipHeapSize | 32 


| net.TcpipHeapMax | 1024MB 


| NFS.MaxVolumes | 256 


| NFS41.MaxVolumes를 참조하십시오 | 256 


| NFS.MaxQueueDepth입니다 | 128 이상 


| NFS.HeartbeatMaxFailures 를 참조하십시오 | 10 


| NFS.HeartbeatFrequency 를 선택합니다 | 12 


| NFS.HeartbeatTimeout | 5 
|===