---
permalink: configure/discover-storage-systems-and-hosts.html 
sidebar: sidebar 
keywords:  
summary: vSphere Client에서 VMware vSphere용 ONTAP 툴을 처음 실행하면 VMware vSphere용 ONTAP 툴이 ESXi 호스트, 해당 LUN 및 NFS 내보내기, 해당 LUN 및 내보내기를 소유한 NetApp 스토리지 시스템을 검색합니다. 
---
= ONTAP tools에서 스토리지 시스템 및 호스트 검색
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere vSphere Client에서 처음 실행하면 ESXi 호스트, 관련 LUN 및 NFS 내보내기, 그리고 이러한 리소스를 소유한 NetApp 스토리지 시스템을 자동으로 검색합니다.

.시작하기 전에
* 모든 ESXi 호스트의 전원이 켜져 있고 연결되어 있는지 확인하세요.
* 검색할 모든 스토리지 가상 머신(SVM)이 실행 중인지 확인하고, 각 클러스터 노드에 사용 중인 스토리지 프로토콜(NFS 또는 iSCSI)에 대해 최소한 하나의 데이터 LIF가 구성되어 있는지 확인합니다.


.이 작업에 대해
새로운 스토리지 시스템을 발견하거나 기존 스토리지 시스템을 업데이트하여 최신 용량 및 설정 세부 정보를 얻을 수 있습니다.  스토리지 시스템 액세스를 위해 ONTAP tools for VMware vSphere 변경할 수도 있습니다.

스토리지 시스템을 검색하는 동안 VMware vSphere용 ONTAP 툴은 vCenter Server 인스턴스에서 관리하는 ESXi 호스트에서 정보를 수집합니다.

.단계
. vSphere Client 홈 페이지에서 * 호스트 및 클러스터 * 를 선택합니다.
. 필요한 데이터 센터를 마우스 오른쪽 버튼으로 클릭하고 * NetApp ONTAP 도구* > *호스트 데이터 업데이트*를 선택합니다.
+
확인 * 대화 상자에서 선택 사항을 확인합니다.

. 상태인 검색된 스토리지 컨트롤러를 `Authentication Failure` 선택하고 * Actions * > * Modify * 를 선택합니다.
. 스토리지 시스템 수정 * 대화 상자에 필요한 정보를 입력합니다.
. 를 사용하는 모든 스토리지 컨트롤러에 대해 4단계와 5단계를 반복합니다 `Authentication Failure` 상태.


검색 프로세스가 완료되면 다음 작업을 수행합니다.

* VMware vSphere용 ONTAP 툴을 사용하여 어댑터 설정 열, MPIO 설정 열 또는 NFS 설정 열에 경고 아이콘을 표시하는 호스트의 ESXi 호스트 설정을 구성합니다.
* 스토리지 시스템 자격 증명을 제공합니다.

