---
permalink: configure/install-nfs-vaai-plug-in.html 
sidebar: sidebar 
keywords:  
summary: 'VMware vSphere용 ONTAP 툴을 사용하여 VAAI\(NetApp NFS Plug-in for VMware vStorage APIs for Array Integration)를 설치할 수 있습니다.' 
---
= ONTAP 도구를 사용하여 NFS VAAI 플러그인 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS vStorage API for Array Integration(NFS VAAI) 플러그인은 VMware vSphere를 NFS 스토리지 어레이에 연결합니다.  ONTAP tools for VMware vSphere 사용하여 VAAI 플러그인을 설치하세요. 이렇게 하면 ESXi 호스트 대신 NFS 스토리지 어레이가 특정 스토리지 작업을 처리할 수 있습니다.

.시작하기 전에
*  https://mysupport.netapp.com/site/products/all/details/nfsplugin-vmware-vaai/downloads-tab["VMware VAAI용 NetApp NFS 플러그인"]설치 패키지를 다운로드합니다.
* ESXi 호스트와 vSphere 7.0U3 최신 패치 이상 버전 및 ONTAP 9.14.1 이상 버전이 있는지 확인합니다.
* NFS 데이터 저장소를 마운트합니다.


.단계
. vSphere Client에 로그인합니다.
. 플러그인 섹션에서 * 바로 가기 * > * NetApp ONTAP tools * 를 선택합니다.
. Settings * > * NFS VAAI Tools * 를 선택합니다.
. 이미 vCenter Server에 VAAI 플러그인을 업로드한 경우, *기존 버전*에서 *변경*을 선택합니다.  아직 업로드하지 않았다면 *업로드*를 선택하세요.
. 파일을 찾아 선택하고 `.vib` * 업로드 * 를 선택하여 ONTAP 도구에 파일을 업로드합니다.
. ESXi 호스트에 설치 * 를 선택하고 NFS VAAI 플러그인을 설치할 ESXi 호스트를 선택한 다음 * 설치 * 를 선택합니다.
+
vSphere Web Client는 플러그인을 설치할 수 있는 ESXi 호스트만 표시합니다. 최근 작업 섹션에서 설치 진행 상황을 모니터링할 수 있습니다.

. 설치 후 ESXi 호스트를 수동으로 다시 시작합니다.
+
ESXi 호스트를 다시 시작하면 ONTAP tools for VMware vSphere NFS VAAI 플러그인을 자동으로 감지하고 활성화합니다.



.다음 단계
NFS VAAI 플러그인을 설치하고 ESXi 호스트를 재부팅한 후 VAAI 복사 오프로드에 대한 NFS 내보내기 정책을 구성합니다.  수출 정책 규칙이 다음 요구 사항을 충족하는지 확인하세요.

* 해당 ONTAP 볼륨은 NFSv4 호출을 허용합니다.
* 루트 사용자는 루트로 유지되며 모든 접합 부모 볼륨에서 NFSv4가 허용됩니다.
* VAAI 지원 옵션은 해당 NFS 서버에서 설정됩니다.


자세한 내용은 다음을 참조하세요. https://kb.netapp.com/on-prem/ontap/DM/VAAI/VAAI-KBs/Configure_the_correct_NFS_export_policies_for_VAAI_copy_offload["VAAI 복사 오프로드에 대한 올바른 NFS 내보내기 정책을 구성합니다"] KB 문서.

.관련 정보
https://docs.netapp.com/us-en/ontap/nfs-admin/support-vmware-vstorage-over-nfs-concept.html["VMware vStorage over NFS 지원"]

https://docs.netapp.com/us-en/ontap/nfs-admin/enable-disable-nfsv40-task.html["NFSv4.0을 사용하거나 사용하지 않도록 설정합니다"]

https://docs.netapp.com/us-en/ontap/nfs-admin/ontap-support-nfsv42-concept.html#nfs-v4-2-security-labels["NFSv4.2에 대한 ONTAP 지원"]
