---
permalink: configure/registration-process.html 
sidebar: sidebar 
keywords:  
summary: ONTAP tools for VMware vSphere 사용하여 vCenter Server 인스턴스에 VASA 공급자를 등록할 수 있습니다. 
---
= ONTAP 도구를 사용하여 vCenter Server 인스턴스에 VASA 공급자 등록
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere 사용하여 VASA 공급자를 vCenter Server 인스턴스에 등록합니다.  이를 통해 스토리지 정책 기반 관리, vVols 지원, ONTAP 시스템의 VMware Live Site Recovery 어플라이언스와의 통합이 가능합니다.

VASA 공급자 설정은 선택한 vCenter Server의 등록 상태를 보여줍니다.

.단계
. vSphere Client에 로그인합니다.
. 플러그인 섹션에서 * 바로 가기 * > * NetApp ONTAP tools * 를 선택합니다.
. *설정* > *VASA 공급자 설정*을 선택하세요.  ONTAP 도구는 VASA 공급자 등록 상태를 등록되지 않음으로 표시합니다.
. VASA Provider를 등록하려면 * 등록 * 버튼을 선택합니다.
. VASA 공급자의 이름과 자격 증명을 입력하세요.  사용자 이름에는 문자, 숫자, 밑줄만 사용할 수 있습니다.  비밀번호 길이를 8~256자 사이로 설정하세요.
. Register * 를 선택합니다.
. 등록이 성공적으로 완료되고 페이지가 새로 고쳐지면 ONTAP 도구는 등록된 VASA 공급자의 상태, 이름, 버전을 표시합니다.


.다음 단계
온보딩된 VASA Provider가 vCenter 클라이언트의 VASA Provider 아래에 표시되는지 확인합니다.

.단계
. vCenter Server 인스턴스로 이동합니다.
. 관리자 자격 증명으로 로그인합니다.
. 스토리지 공급자 * > * 구성 * 을 선택합니다. 온보드된 VASA Provider가 올바르게 나열되는지 확인합니다.

