---
permalink: release-notes/whats-new.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 10.5, ONTAP tools for VMware vSphere' 
summary: ONTAP tools for VMware vSphere 에서 사용할 수 있는 새로운 기능에 대해 알아보세요. 
---
= ONTAP tools for VMware vSphere 의 새로운 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere 에서 사용할 수 있는 새로운 기능에 대해 알아보세요.

* *플랫폼 자격*


ONTAP tools for VMware vSphere ASA r2 시스템에 대한 지원을 추가하여 최신 하드웨어 및 소프트웨어 구성과의 호환성을 제공합니다.  이 릴리스에는 ONTAP 9.16.1 및 9.17.1과의 통합도 포함되어 지원 환경이 확장되었습니다.

* *VMware 자격 및 인증*


ONTAP tools for VMware vSphere 현재 VMware 상호 운용성 인증 표준을 준수하며 ESXi 호스트와 vCenter Server를 모두 지원합니다.

* * MetroCluster 지원*


이 릴리스에서는 MetroCluster 구성에 대한 지원이 도입되어 고가용성과 재해 복구 기능이 향상되었습니다.

* *보안 및 인증서 관리*


이번 릴리스에서는 자체 서명 인증서의 관리가 간소화되어 사용자 경험과 보안 표준 준수가 모두 향상되었습니다.  ONTAP tools for VMware vSphere ONTAP 및 ONTAP 도구를 보호하기 위해 향상된 인증서 검증 워크플로를 제공합니다.

* *복제 향상*


이 릴리스에서는 ASA r2 시스템의 SRA 및 SnapMirror 활성 동기화를 포함한 계층적 일관성 그룹을 사용한 VMFS 복제를 지원합니다.  데이터 보호 및 복구를 개선하기 위해 0 RPO 백업을 지원합니다.

* *업그레이드 및 마이그레이션*


ONTAP tools for VMware vSphere 의 이전 버전에서 ONTAP tools for VMware vSphere 로의 업그레이드 및 마이그레이션 프로세스는 원활하고 효율적으로 설계되어 가동 중지 시간을 최소화하고 원활한 전환을 보장합니다.



== 지원되는 ONTAP 플랫폼 및 vCenter Server 버전

ONTAP tools for VMware vSphere 10.5 P1은 SRA 및 SnapMirror active sync 구성 요소에 대한 vCenter 고가용성(HA) 구성을 지원합니다. 이 구성에서는 vVols가 지원되지 않습니다. HA 장애 조치 중에는 vCenter가 몇 분 동안 사용할 수 없을 수 있습니다. 대규모 환경이거나 오류가 발생한 경우, 장애 조치 시간이 15분을 초과할 수 있습니다.

자세한 내용은 https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-0/vsphere-availability/vcenter-server-high-availability.html["vCenter 고가용성 문서"^]를 참조하십시오. vCenter HA에 대한 질문은 https://support.broadcom.com/["Broadcom 지원"^]에 문의하십시오.

버전 호환성에 대한 최신 세부 정보는 다음을 참조하세요. https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^] .
