---
permalink: manage/delete-ds.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: 데이터 저장소 삭제 작업은 데이터 저장소를 삭제합니다. NFS 또는 VMFS 데이터 저장소의 경우 데이터 저장소를 사용 중인 VM 목록이 포함된 대화 상자가 나타납니다. 
---
= 데이터 저장소를 삭제합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 페이지에서는 vCenter Server에서 ONTAP 도구를 사용하여 NFS, VMFS 또는 vVols 데이터스토어를 삭제하는 방법을 설명합니다.

데이터 저장소를 삭제하면 데이터 저장소 유형에 따라 다음 작업이 수행됩니다.

* vVol 컨테이너가 마운트 해제되었습니다.
* igroup이 사용되지 않으면 iqn이 igroup에서 제거됩니다.
* vVol 컨테이너가 삭제되었습니다.
* Flex 볼륨은 스토리지 어레이에 남아 있습니다.


선택한 데이터스토어에 vVols 없는 경우에만 데이터스토어를 삭제할 수 있습니다.

.단계
. vSphere Client에 로그인합니다.
. 호스트 시스템, 호스트 클러스터 또는 데이터 센터를 마우스 오른쪽 버튼으로 클릭하고 * NetApp ONTAP 도구* > *데이터 저장소 삭제*를 선택합니다.
+

NOTE: 가상 머신에서 사용하는 데이터 저장소는 삭제할 수 없습니다.  삭제하기 전에 가상 머신을 다른 데이터 저장소로 이동합니다.  보호된 호스트 클러스터의 일부인 경우 볼륨을 삭제할 수 없습니다.

+
.. NFS 또는 VMFS 데이터 저장소의 경우 데이터 저장소를 사용하는 VM 목록이 있는 대화 상자가 나타납니다.
.. VMFS 데이터 저장소에 연결된 가상 머신이 없으면 확인 대화 상자가 표시됩니다.  호스트 클러스터 보호가 활성화되어 있고 AFD 관계가 존재하는 경우 보조 저장소 요소를 정리할 수 있습니다.
.. ASA r2 시스템의 보호된 VMFS 데이터 저장소의 경우 삭제하기 전에 보호를 제거하세요. ONTAP 9.17.1 및 ONTAP tools for VMware vSphere 부터 보호된 데이터 저장소를 삭제할 수 있습니다.  보호 그룹에 있는 유일한 데이터 저장소인 경우 호스트 클러스터 보호가 자동으로 제거됩니다.
.. vVols 데이터 저장소의 경우 vVols 가 없는 경우에만 데이터 저장소를 삭제할 수 있습니다.  *데이터 저장소 삭제* 대화 상자에는 ONTAP 클러스터에서 볼륨을 제거하는 옵션이 포함되어 있습니다.
.. ASA r2 시스템의 vVols 데이터 저장소의 경우 *데이터 저장소 삭제* 옵션을 사용하여 ONTAP 에서 백업 볼륨을 삭제할 수 없습니다.


. ONTAP 스토리지에서 백업 볼륨을 삭제하려면 * Delete volumes on ONTAP cluster * 를 선택합니다.
+

NOTE: 보호된 호스트 클러스터의 일부인 통합 ONTAP 스토리지의 VMFS 데이터 저장소의 경우 ONTAP 클러스터에서 볼륨을 삭제할 수 없습니다.



NFS, VMFS 또는 vVols 데이터 저장소를 삭제해도 상위 igroup은 ONTAP 시스템에 남아 있습니다. 어떤 LUN에도 매핑되지 않은 자식 igroup은 자동으로 삭제됩니다. ONTAP 도구는 매핑되지 않은 기본 상위 igroup을 제거하기 위해 매일 정리를 수행합니다. ONTAP 에서 사용자 정의 상위 igroup을 수동으로 삭제합니다.  ONTAP 도구는 오래된 부모 igroup을 재사용할 수 없습니다.
