---
permalink: manage/edit-hostcluster-protection.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: 보호된 호스트 클러스터의 SnapMirror 관계를 편집할 수 있습니다. 관계를 추가, 수정 및 삭제할 수 있습니다. 하지만 일관성 그룹 이름을 편집할 수는 없습니다. 
---
= ONTAP tools에서 보호된 호스트 클러스터를 수정합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
단일 워크플로에서 호스트 클러스터의 보호 설정을 변경할 수 있습니다.  다음과 같은 변경 사항이 지원됩니다.

* 보호된 클러스터에 새 데이터 저장소 또는 호스트를 추가합니다.
* 보호 설정에 새 SnapMirror 관계를 추가합니다.
* 보호 설정에서 기존 SnapMirror 관계를 삭제합니다.
* 기존 SnapMirror 관계 수정



NOTE: 호스트 클러스터에 대한 보호를 생성, 편집 또는 삭제한 후에는 변경 사항을 반영하기 위해 저장소 검색을 수행해야 합니다.  저장소 검색을 수행하지 않으면 주기적 저장소 검색이 트리거된 후에 변경 사항이 반영됩니다.



== 호스트 클러스터 보호를 모니터링합니다

각 보호된 호스트 클러스터의 보호 상태, SnapMirror 관계, 데이터 저장소 및 SnapMirror 상태를 모니터링합니다.

.단계
. vSphere Client에 로그인합니다.
. * NetApp ONTAP 도구* > *보호* > *호스트 클러스터 관계*로 이동합니다.
+
보호 열에는 보호 상태를 나타내는 아이콘이 표시됩니다.

. 자세한 내용을 보려면 아이콘 위에 마우스를 올려 놓으십시오.




== 새 데이터 저장소 또는 호스트를 추가합니다

vCenter 사용자 인터페이스를 사용하여 보호된 클러스터에 호스트를 추가하거나 데이터 저장소를 만듭니다.

.단계
. vSphere Client에 로그인합니다.
. 보호된 클러스터의 속성을 편집하려면 다음 중 하나를 수행합니다
+
.. * NetApp ONTAP 도구* > *보호* > *호스트 클러스터 관계*로 이동하여 클러스터 옆에 있는 줄임표 메뉴를 선택하고 *편집*을 선택합니다.
.. 호스트 클러스터를 마우스 오른쪽 버튼으로 클릭하고 * NetApp ONTAP 도구* > *클러스터 보호*를 선택합니다.


. vCenter 사용자 인터페이스에서 데이터스토어를 생성하면 보호되지 않은 것으로 나타납니다.  대화 상자에서 클러스터의 모든 데이터 저장소와 해당 보호 상태를 볼 수 있습니다.  보호 기능을 활성화하려면 *보호* 버튼을 선택하세요.
+

NOTE: vCenter Server 사용자 인터페이스에서 데이터스토어를 만든 후 개요 페이지에서 *검색*을 선택하면 해당 데이터스토어가 호스트 클러스터에서 보호 후보로 표시됩니다.  다음 주기적 보호 검색 후 보호 상태가 보호됨으로 업데이트됩니다.

. 새로운 ESXi 호스트를 추가하면 보호 상태가 부분적으로 보호됨으로 표시됩니다.  SnapMirror 설정에서 줄임표 메뉴를 선택하고 *편집*을 선택하여 새로 추가된 ESXi 호스트의 근접성을 설정합니다.
+

NOTE: 비동기 관계의 경우, 3차 사이트의 대상 SVM을 동일한 인스턴스에 추가할 수 없기 때문에 ONTAP 도구에서 편집이 지원되지 않습니다.  관계 구성을 수정하려면 대상 SVM에서 시스템 관리자나 CLI를 사용합니다.

. 변경 사항을 적용한 후 *저장*을 선택하세요.
. Protect Cluster * 창에서 변경 사항을 확인할 수 있습니다.


ONTAP 도구는 vCenter 작업을 생성하고, *최근 작업* 패널에서 진행 상황을 추적할 수 있습니다.



== 새 SnapMirror 관계를 추가합니다

.단계
. vSphere Client에 로그인합니다.
. 보호된 클러스터의 속성을 편집하려면 다음 중 하나를 수행합니다
+
.. * NetApp ONTAP 도구* > *보호* > *호스트 클러스터 관계*로 이동하여 클러스터에 대한 줄임표 메뉴를 선택하고 *편집*을 선택합니다.
.. 호스트 클러스터를 마우스 오른쪽 버튼으로 클릭하고 * NetApp ONTAP 도구* > *클러스터 보호*를 선택합니다.


. 관계 추가 * 를 선택합니다.
. 새 관계를 * Asynchronous * 또는 * AutomatedFailOverDuplex * 정책 유형으로 추가합니다.
. protect * 를 선택합니다.
+
Protect Cluster * 창에서 변경 사항을 확인할 수 있습니다.



ONTAP 도구는 vCenter 작업을 생성하고, *최근 작업* 패널에서 진행 상황을 추적할 수 있습니다.



== 기존 SnapMirror 관계를 삭제합니다

SnapMirror 비동기 관계를 삭제하려면 보조 사이트 SVM 또는 클러스터가 ONTAP tools for VMware vSphere 에서 스토리지 백엔드로 추가되었는지 확인하세요.  모든 SnapMirror 관계를 한 번에 삭제할 수는 없습니다.  관계를 삭제하면 ONTAP 클러스터에서도 해당 관계가 제거됩니다.  자동 장애 조치 듀플렉스 SnapMirror 관계를 삭제하면 시스템은 대상 데이터 저장소의 매핑을 해제하고 대상 ONTAP 클러스터에서 일관성 그룹, LUN, 볼륨 및 igroup을 삭제합니다.

관계를 삭제하면 시스템은 보조 사이트를 다시 스캔하여 호스트에서 매핑되지 않은 LUN을 활성 경로로 제거합니다.

.단계
. vSphere Client에 로그인합니다.
. 보호된 클러스터의 속성을 편집하려면 다음 중 하나를 수행합니다
+
.. * NetApp ONTAP 도구* > *보호* > *호스트 클러스터 관계*로 이동하여 클러스터에 대한 줄임표 메뉴를 선택하고 *편집*을 선택합니다.
.. 호스트 클러스터를 마우스 오른쪽 버튼으로 클릭하고 * NetApp ONTAP 도구* > *클러스터 보호*를 선택합니다.


. SnapMirror 설정 아래에서 줄임표 메뉴를 선택하고 * 삭제 * 를 선택합니다.
+
** 보호된 호스트 클러스터의 비동기 정책 유형 기반 관계를 삭제하는 경우 3차 스토리지 클러스터에서 스토리지 요소를 수동으로 제거해야 합니다.  저장소 요소에는 일관성 그룹, 볼륨( ONTAP 시스템용), 저장소 단위(LUN/네임스페이스) 및 스냅샷이 포함됩니다.
** 보호된 호스트 클러스터의 AFD(자동 장애 조치 이중화) 정책 기반 관계를 삭제하는 경우 인터페이스에서 직접 보조 스토리지의 관련 스토리지 요소를 제거하도록 선택할 수 있습니다.
** AFD(자동 장애 조치 이중화) 정책 기반 관계를 삭제하고 일관성 그룹이 이제 애플리케이션 수준 백업에 대해 계층적이면 백업 영향에 대한 경고가 나타납니다.  계속하려면 확인하세요.  확인 후, 보조 저장소에서 연관된 저장 요소를 삭제합니다.  제거하지 않으면 보조 사이트에 그대로 남아 있습니다.




ONTAP 도구는 vCenter 작업을 생성하고, *최근 작업* 패널에서 진행 상황을 추적할 수 있습니다.



== 기존 SnapMirror 관계 수정

SnapMirror 비동기 관계를 수정하려면 보조 사이트 SVM 또는 클러스터가 ONTAP tools for VMware vSphere 에서 스토리지 백엔드로 추가되었는지 확인하세요.  자동 장애 조치 Duplex SnapMirror 관계의 경우 균일한 구성에 대한 호스트 근접성이나 비균일한 구성에 대한 호스트 액세스를 업데이트할 수 있습니다.  비동기 및 자동 장애 조치 이중 정책 유형 간의 변경은 지원되지 않습니다.  클러스터에서 새로 검색된 호스트에 대한 근접성 또는 액세스 설정을 구성할 수 있습니다.


NOTE: 기존 SnapMirror 비동기 관계는 편집할 수 없습니다.

.단계
. vSphere Client에 로그인합니다.
. 보호된 클러스터의 속성을 편집하려면 다음 중 하나를 수행합니다
+
.. * NetApp ONTAP 도구* > *보호* > *호스트 클러스터 관계*로 이동하여 클러스터에 대한 줄임표 메뉴를 선택하고 *편집*을 선택합니다.
.. 호스트 클러스터를 마우스 오른쪽 버튼으로 클릭하고 * NetApp ONTAP 도구* > *클러스터 보호*를 선택합니다.


. AutomatedFailOverDuplex 정책 유형이 선택된 경우 호스트 근접성 또는 호스트 액세스 세부 정보를 추가합니다.
. 보호 * 버튼을 선택합니다.


ONTAP 도구는 vCenter 작업을 생성합니다.  *최근 작업* 패널에서 진행 상황을 추적하세요.
