---
permalink: manage/edit-appliance-settings.html 
sidebar: sidebar 
keywords:  
summary: ONTAP 도구 관리자를 사용하여 관리자 암호를 변경할 수 있습니다. 
---
= 어플라이언스 설정을 편집합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools Manager를 사용하여 노드 크기를 확장하고, 서비스를 관리하고, VMware vSphere용 ONTAP 툴을 HA(고가용성) 설정으로 업그레이드할 수 있습니다.

ONTAP 툴 어플라이언스는 처음에 단일 노드 비 HA 구성으로 구축됩니다. 어플라이언스 설정 편집 * 창에서 구성을 편집할 수 있습니다.

* 시작하기 전에 *

제공하는 OVA 템플릿의 OVA 버전이 첫 번째 노드와 같은지 확인합니다.

* 단계 *

. 웹 브라우저에서 ONTAP 도구 관리자를 실행합니다. `\https://loadBalancerIP:8443/virtualization/ui/`
. 구축 중에 제공한 VMware vSphere 관리자 자격 증명용 ONTAP 툴을 사용하여 로그인합니다.
. 개요 섹션에서 * 어플라이언스 설정 편집 * 을 선택합니다.
. 서비스 * 섹션에서 필요에 따라 VASA Provider, VVol 구성 가져오기, SRA(재해 복구) 등의 옵션 서비스를 활성화할 수 있습니다.
+
서비스를 처음 설정할 때는 VASA Provider/SRA 자격 증명을 생성해야 합니다. vCenter Server에서 VASA Provider/SRA 서비스를 등록하거나 설정하는 데 사용됩니다.

+

NOTE: 선택적 서비스를 사용하지 않도록 설정하려면 ONTAP 툴을 통해 관리되는 vCenter Server에서 해당 서비스를 사용하지 않도록 설정합니다.

+
* Allow import of vVols configuration * 옵션은 VASA Provider 서비스가 활성화된 경우에만 표시됩니다. 이 옵션을 사용하면 ONTAP 툴 9.x에서 ONTAP 툴 10.3으로 VVol 데이터를 마이그레이션할 수 있습니다.

. 구성 * 섹션에서 각 ONTAP 툴 노드 크기를 확장하고 요구사항에 따라 HA 구성을 활성화할 수 있습니다. 변경하려면 vCenter Server 자격 증명이 필요합니다.
+
ONTAP 도구가 HA 구성으로 되어 있으면 콘텐츠 라이브러리 세부 정보를 변경할 수 있습니다. 새 편집 제출에 대한 암호를 다시 입력해야 합니다.

+

NOTE: ONTAP 도구 노드 크기만 확장할 수 있습니다. 노드를 현재 크기에서 더 작은 크기로 축소할 수 없습니다. HA가 아닌 경우에 지원되는 최대 구성은 보통입니다. HA의 경우 중형 및 대형 구성이 지원됩니다.

. HA 전환 버튼을 사용하여 HA 구성을 활성화합니다. HA 구성을 선택하면 HA 관련 입력에 대한 추가 * HA 설정 * 페이지가 나타납니다.
+
** 컨텐츠 라이브러리는 ONTAP 툴 노드 VM이 실행되고 있는 동일한 vCenter Server에 속해야 합니다. vCenter Server 자격 증명은 어플라이언스 변경 사항을 확인하기 위해 OVA 템플릿을 다운로드하는 데 사용됩니다.
** HA 배포를 사용하려면 ONTAP 툴을 호스팅하는 가상 시스템을 ESXi 호스트에 직접 배포해서는 안 됩니다. 대신, 클러스터 또는 리소스 풀에 구축되어야 합니다.
** 사용하도록 설정한 후에는 HA 구성에서 HA가 아닌 단일 노드 구성으로 되돌릴 수 없습니다.


. 어플라이언스 설정 편집 * 창의 * HA 설정 * 섹션에서 노드 2 및 노드 3의 세부 정보를 입력할 수 있습니다. 노드 1은 OVA의 일부로 구축되는 ONTAP 툴 기본 노드입니다. VMware vSphere용 ONTAP 툴은 HA 설정에서 3개의 노드를 지원합니다.
+

NOTE: 대부분의 입력 옵션은 워크플로우의 용이성을 위해 노드 1 네트워크 세부 정보로 미리 채워져 있습니다. 그러나 마법사의 마지막 페이지로 이동하기 전에 입력 데이터를 편집할 수 있습니다. 첫 번째 노드에서 IPv6 주소가 활성화된 경우에만 다른 두 노드에 대한 IPv6 세부 정보를 입력할 수 있습니다.

+
ESXi 호스트에 ONTAP 툴 VM이 하나만 포함되어 있는지 확인합니다. 입력은 다음 창으로 이동할 때마다 검증됩니다.

. summary * 섹션에서 세부 사항을 검토하고 * Save * 를 선택하여 변경 사항을 적용합니다.


개요 * 페이지에는 배포 상태가 표시됩니다. 작업 ID를 사용하여 작업 보기에서 어플라이언스 설정 편집 작업 상태를 추적할 수도 있습니다.

HA 구축에 실패하고 새 노드의 상태가 'New'로 표시되면 HA 활성화 작업을 다시 시도하기 전에 vCenter에서 새 VM을 삭제합니다.

왼쪽 패널의 * Alerts * 탭에는 VMware vSphere용 ONTAP 툴에 대한 경고가 표시됩니다.
