---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords:  
summary: 데이터 센터에 있는 기존 가상 머신을 마이그레이션할 때 고려해야 할 몇 가지 사항이 있습니다. 
---
= ONTAP tools를 사용한 가상 머신 마이그레이션 및 복제 시 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere는 컴퓨팅 전용(vMotion), 스토리지 전용(Storage vMotion) 및 모든 데이터스토어에 걸친 컴퓨팅 및 스토리지 결합 마이그레이션을 포함하여 모든 주요 유형의 가상 머신 마이그레이션을 지원합니다. 이 항목에서는 기본 데이터스토어 유형에 관계없이 가상 머신의 성공적인 마이그레이션 및 복제를 보장하기 위한 주요 고려 사항과 모범 사례를 설명합니다.



== 보호된 가상 시스템을 마이그레이션합니다

보호된 가상 머신을 다음 위치로 마이그레이션할 수 있습니다.

* 다른 ESXi 호스트의 동일한 데이터 저장소
* 동일한 ESXi 호스트에 있는 다른 호환 데이터 저장소
* 다른 ESXi 호스트에 있는 호환 가능한 다른 데이터 저장소


가상 머신을 다른 FlexVol 볼륨으로 마이그레이션하면 시스템은 해당 볼륨의 메타데이터 파일을 가상 머신 정보로 업데이트합니다. 가상 머신을 다른 ESXi 호스트로 마이그레이션하되 스토리지는 동일하게 유지하는 경우, 기본 FlexVol 볼륨의 메타데이터 파일은 수정되지 않습니다.

가상 머신 마이그레이션에 대한 자세한 내용은 Broadcom 설명서를 참조하십시오. https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-0/vcenter-and-host-management/migrating-virtual-machines-host-management.html["vSphere 가상 머신 마이그레이션"]



== 보호된 가상 머신의 클론을 생성합니다

보호된 가상 컴퓨터를 다음 컴퓨터에 클론 복제할 수 있습니다.

* 복제 그룹을 사용하는 동일한 FlexVol 볼륨의 동일한 컨테이너
+
동일한 FlexVol 볼륨의 메타데이터 파일이 복제된 가상 머신의 세부 정보로 업데이트됩니다.

* 복제 그룹을 사용하는 다른 FlexVol 볼륨의 동일한 컨테이너
+
복제된 가상 머신이 배치된 FlexVol 볼륨에서 메타데이터 파일이 복제된 가상 머신 세부 정보로 업데이트됩니다.

* 다른 컨테이너 또는 vVols 데이터 저장소
+
복제된 가상 머신이 배치된 FlexVol 볼륨에서 메타데이터 파일이 가상 머신 세부 정보로 업데이트됩니다.



VMware는 현재 VM 템플릿으로 복제된 가상 머신을 지원하지 않습니다.

보호된 가상 머신의 클론의 클론이 지원됩니다.

자세한 내용은 Broadcom 설명서 https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html["클론 생성을 위한 가상 머신 생성"]를 참조하십시오.



== 가상 머신 스냅샷

ONTAP tools는 표준 VMware 워크플로를 통해 가상 머신 스냅샷을 지원합니다. 스냅샷은 테스트 및 패치 준비와 같은 사용 사례를 위한 단기 롤백 지점입니다. 스냅샷은 백업 또는 복제 기반 데이터 보호를 대체하는 것이 아닙니다. 스냅샷에서 가상 머신을 장기간 실행하면 불안정성 및 데이터 손실이 발생할 수 있습니다.

지원되는 모든 데이터스토어 유형에서 크래시 일관성 스냅샷(메모리 상태가 없는 스냅샷으로, 가상 머신을 일관된 상태로 다시 시작하는 데 사용할 수 있음)을 생성할 수 있습니다. VMware Tools를 사용하여 캡처하기 전에 메모리 내 데이터를 디스크에 플러시하는 정지 스냅샷도 지원됩니다. 스냅샷 유형 및 동작에 대한 개요는 https://knowledge.broadcom.com/external/article/342618/overview-of-virtual-machine-snapshots-in.html["vSphere의 가상 머신 스냅샷 개요"]를 참조하십시오.


NOTE: 메모리 스냅샷은 실행 중인 메모리 상태를 캡처하고 가상 머신을 일시적으로 중단시킵니다. ONTAP tools 워크플로에서는 지원되지 않습니다. 가상 머신에 메모리 스냅샷이 있는 경우 ONTAP tools에서 관리하는 일관성 그룹 또는 호스트 클러스터 관계에 가상 머신을 포함하기 전에 삭제해야 합니다.

ASA r2 스토리지 시스템에서 가상 머신 스냅샷의 동작은 다른 스토리지 유형과 다릅니다. 스냅샷은 읽기 전용입니다. 가상 머신을 시작하면 VASA Provider는 읽기 전용 스냅샷에서 LUN을 생성하고 IOPS를 활성화합니다. 가상 머신을 끄면 VASA Provider는 LUN을 삭제하고 IOPS를 비활성화합니다.

가상 머신 스냅샷 관리에 대한 자세한 내용은 Broadcom 설명서 https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-0/vsphere-virtual-machine-administration/managing-virtual-machinesvsphere-vm-admin/using-snapshots-to-manage-virtual-machinesvsphere-vm-admin.html["스냅샷으로 가상 머신 관리"]를 참조하십시오.
