---
permalink: manage/mount-datastores-on-host.html 
sidebar: sidebar 
keywords:  
summary: 데이터 저장소를 마운트하면 추가 호스트에 대한 스토리지 액세스가 제공됩니다. VMware 환경에 호스트를 추가한 후 추가 호스트에 데이터 저장소를 마운트할 수 있습니다. 
---
= NFS 및 VMFS 데이터 저장소를 마운트합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 저장소를 마운트하면 추가 호스트에 대한 스토리지 액세스가 제공됩니다. VMware 환경에 호스트를 추가한 후 추가 호스트에 데이터 저장소를 마운트할 수 있습니다.


NOTE: 다음을 사용하여 새 ESXi 호스트를 추가하는 경우 https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-0/use-quickstart-to-add---host-to-a-cluster.html["vSphere 클러스터 워크플로에 ESX 호스트 추가"] ONTAP 도구에 표시되기 전에 예약된 호스트 검색이 완료될 때까지 기다리세요. 또는 NetApp ONTAP 도구 개요 화면에서 수동으로 검색을 실행할 수 있습니다.

.이 작업에 대해
* vSphere Client 버전 및 선택한 데이터 저장소 유형에 따라 일부 마우스 오른쪽 버튼 클릭 작업이 해제되거나 사용할 수 없습니다.
+
** vSphere Client 8.0 이상 버전을 사용하는 경우 마우스 오른쪽 버튼 클릭 옵션 중 일부가 표시되지 않습니다.
** vSphere 7.0U3에서 vSphere 8.0 버전까지 옵션이 표시되더라도 작업이 비활성화됩니다.


* 호스트 클러스터가 균일한 구성으로 보호되는 경우 vSphere는 마운트 데이터스토어 옵션을 비활성화합니다.


.단계
. vSphere Client 홈 페이지에서 * 호스트 및 클러스터 * 를 선택합니다.
. 왼쪽 탐색 창에서 호스트가 포함된 데이터 센터를 선택합니다.
. 호스트 또는 호스트 클러스터에 NFS/VMFS 데이터 저장소를 마운트하려면 마우스 오른쪽 버튼을 클릭하고 * NetApp ONTAP 도구* > *데이터 저장소 마운트*를 선택합니다.
. 마운트할 데이터 저장소를 선택하고 * Mount * 를 선택합니다.


.다음 단계
최근 작업 패널에서 진행 상황을 추적할 수 있습니다.

.관련 주제
link:../manage/add-vsphere-host.html["새로운 VMware vSphere 호스트 추가"]
