---
permalink: manage/recover-backup.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere 10.3용 ONTAP 툴부터는 어플라이언스가 동적 스토리지 프로비저닝을 사용하므로 RPO를 0으로 달성할 수 없습니다. 하지만 거의 0에 가까운 RPO를 달성할 수 있습니다. 
---
= ONTAP 도구 설정 복구
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere 부터 백업 기능이 기본적으로 활성화됩니다.

ONTAP tools for VMware vSphere 배포하는 데이터 저장소에는 백업 파일이 저장됩니다.  ONTAP 도구 IP 주소(점은 밑줄로 대체되고 _OTV_backup_으로 접미사 추가)의 이름을 딴 폴더에는 가장 최근의 두 백업 파일(_OTV_backup_1.tar.enc_ 및 _OTV_backup_2.tar.enc_)과 최신 백업의 이름이 포함된 정보 파일(_OTV_backup_info.txt_)이 보관됩니다.

새로운 가상 머신이 동일한 ONTAP 도구 IP 주소를 사용하고 활성화된 서비스, 노드 크기, HA 모드를 포함한 초기 시스템 구성과 일치하는지 확인합니다.

.단계
. 원래 가상 머신의 데이터 저장소에서 백업 파일을 로컬 시스템으로 다운로드합니다.
+
.. 저장소 섹션으로 이동하여 가상 머신의 백업 파일이 포함된 데이터 저장소를 선택합니다.
.. 파일 * 섹션을 선택합니다.
.. 필요한 백업 디렉토리를 다운로드합니다.


. 기존 가상 머신의 전원을 끕니다.  그런 다음 원래 배포와 동일한 OVA 파일을 사용하여 새 가상 머신을 배포합니다.
. vCenter Server에서 유지 관리 콘솔을 엽니다.
. 유지보수 사용자로 로그인합니다.
. 를 `4` 입력하여 * 지원 및 진단 * 을 선택합니다.
. Enter 키를 `2` 눌러 * 원격 진단 액세스 활성화 * 옵션을 선택하고 진단 액세스에 사용할 새 암호를 만듭니다.
. 다운로드한 디렉토리에서 백업 파일을 선택하세요.  최신 백업을 확인하려면 _OTV_backup_info.txt_ 파일을 참조하세요.
. 다음 명령을 사용하여 백업 파일을 새 가상 머신으로 전송합니다.  메시지가 표시되면 진단 비밀번호를 입력하세요.
+
[listing]
----
scp <OTV_backup_X.tar.enc> diag@<node_ip>:/home/diag/system_recovery.tar.enc
----
+

NOTE: 명령에 언급된 대상 경로와 파일 이름(/home/diag/system_recovery.tar.enc)을 변경하지 마세요.

. 백업 파일이 전송된 후 진단 셸에 로그인하여 다음 명령을 실행합니다.
+
[listing]
----
sudo perl /home/maint/scripts/post-deploy-upgrade.pl -recovery
----
+
로그는 _/var/log/post-deploy-upgrade.log_file에 기록됩니다.



복구를 완료하면 ONTAP 도구가 서비스와 vCenter 개체를 복원합니다.
